### ISSUE TITLE
DragEvent on Safari

### ISSUE THREAD

**Issue by jurkat** [pIvan/file-upload#41]
Hello,

I get the following error when I call my app under Safari:
ReferenceError: Can't find variable: DragEvent

Unfortunately I cannot do without safari even for mobile. Is there a wokraround for this problem?

Darg and Drop is not important, but changing the uploader is a lot of work.

Thanks

**Comment by jurkat** [comment]
It's working with Version 1.5.2

**Comment by pIvan** [comment]
Hi @jurkat,
please could you tell me on which version this doesn't work?

Thanks

**Comment by jurkat** [comment]
I tried it on Version 2.0.2 and 2.0.3.

The Error is located in my vendor-es2015.js, but maybe, this code snipped, where the error is located (4th row) can help you:

`Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__decorate"])([
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["HostListener"])('drop', ['$event']),
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:type", Function),
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [DragEvent]),
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:returntype", void 0)
], FileUploadComponent.prototype, "onDrop", null);`

**Comment by pIvan** [comment]
@jurkat can you paste me the whole error, code which you paste was not changed from
the first version until current, also do you have it online?
Whether it appears on the [demo](https://pivan.github.io/file-upload/) page also?

**Comment by pIvan** [comment]
Hi @jurkat, What error says "ReferenceError: Can't find variable: DragEvent" but 
DragEvent is just the interface which should not be in compiled code, 
the issue could only be in a compilation.
Can you paste here error from browser console or give some more info about problem?

**Comment by jurkat** [comment]
Hi @pIvan, sorry for my late response. 
No, it's not online. After i recognize, that it works with version 1.5 i switched..
I tried to install your package on an angular stackblitz but got:

```
Error in ~/src/main.ts
ngcc failed to run on @iplab/ngx-file-upload@2.0.4.
```

What you said about interface made me think. This error only occours while live reload and after building for staging. Bulding in Production let the error omit. So it dont appear on the demo site.

This is the whole browser error:


```
./node_modules/@iplab/ngx-file-upload/__ivy_ngcc__/fesm2015/iplab-ngx-file-upload.js | @ | vendor-es2015.js:85503
-- | -- | --
__webpack_require__ | @ | runtime-es2015.js:80
./src/app/app.module.ts | @ | main-es2015.js:195
__webpack_require__ | @ | runtime-es2015.js:80
./src/main.ts | @ | main-es2015.js:6104
__webpack_require__ | @ | runtime-es2015.js:80
(anonymous function) | @ | main-es2015.js:6126
__webpack_require__ | @ | runtime-es2015.js:80
checkDeferredModules | @ | runtime-es2015.js:46
module code | @ | main-es2015.js:1
evaluate | @ | [native code]:1
moduleEvaluation | @ | [native code]:1
(anonymous function) | @ | [native code]:1
promiseReactionJob

```

This are the setting from the angular.json

```
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            },
            "staging": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.stage.ts"
                }
              ]
            }
```

**Comment by pIvan** [comment]
Hi @jurkat, thanks for all the information you provided, 
I'm busy this week, but I'll try to fix it as soon as I catch some free time

**Comment by Ovaro** [comment]
@pIvan Same here. Looks like we need to replace every DragEvent with any.

**Comment by clampinou** [comment]
Hi @pIvan, same problem here but if you're working on it, I'll wait :-) thank you very much for your module and your efficacy !

**Comment by pIvan** [comment]
Hi could you just confirm which version of Typescript do you have?
I have made change and remove all DragEvent types, 
that should fix the problem with typescript lib definition file.

**Comment by clampinou** [comment]
Hi,
I'm on typescript 3.6.4. But I still have the error on Safari. It seems that a last DragEvent type is still here. Maybe with the screenshot it will help :)
<img width="653" alt="Capture d’écran 2020-06-04 à 15 11 35" src="https://user-images.githubusercontent.com/14886803/83760856-d0a3c680-a675-11ea-8d05-d97c22bffd38.png">

**Comment by pIvan** [comment]
Yeah, I didn't replace them all, sorry I'm working and wanted to change this fast. Give me few minutes.
Typescript version on which library is made is 3.7.5 :)

**Comment by pIvan** [comment]
Please can you try version 2.0.6?

**Comment by clampinou** [comment]
I need the 3.6 to use some other libraries that not support 3.7 yet. A lot of people are not as reactive as you lol ! 😂

I've just tested it and everything is ok for me on Safari now ! Thank you very much ! 🙏

**Comment by Ovaro** [comment]
Thanks @pIvan ! Works perfectly on Safari now.
